# Generated by Django 6.0 on 2026-02-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('predicted_quantity', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('target_month', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-prediction_date', '-predicted_quantity'],
            },
        ),
    ]
