# Generated by Django 6.0 on 2025-12-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='condition',
            field=models.CharField(blank=True, choices=[('new_unused', 'New (Unused)'), ('like_new', 'Like New'), ('gently_used', 'Gently Used'), ('used_functional', 'Used but Functional'), ('refurbished', 'Refurbished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='used_duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
