# Generated by Django 6.0 on 2025-12-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation_condition_donation_used_duration_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationimage',
            name='image',
        ),
        migrations.AddField(
            model_name='donationimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
