# Generated by Django 6.0 on 2026-01-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_donationimage_image_donationimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
