# Generated by Django 6.0 on 2026-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donation_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('item', 'Physical Item'), ('fundraiser', 'Fundraiser')], default='item', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='donation',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
