# Generated by Django 6.0 on 2026-02-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_donationtransaction'),
        ('receiver', '0007_alter_donationorder_status_volunteerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='fulfilled_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='receiver.itemrequest'),
        ),
    ]
