# Generated by Django 6.0 on 2026-02-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_donation_fulfilled_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationTransaction',
        ),
    ]
