import "./AdminReport.css";
import { useEffect, useState } from "react";
import api from "../../../api/api";

const AdminReport = () => {
  const [reports, setReports] = useState([]);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loading, setLoading] = useState(true);

  // 🔹 Fetch all reports
  const fetchReports = () => {
    setLoading(true);
    api
      .get("analytics/reports/")
      .then((res) => {
        setReports(res.data);
        if (res.data.length > 0) {
          setSelectedReport(res.data[0]); // latest
        }
      })
      .catch((err) => {
        console.error("Failed to load reports", err);
      })
      .finally(() => setLoading(false));
  };

  // 🔹 Generate new report
  const handleGenerateReport = () => {
    setLoading(true);
    api
      .post("analytics/reports/generate/", { days: 30 })
      .then(() => fetchReports())
      .catch((err) => {
        console.error("Failed to generate report", err);
      })
      .finally(() => setLoading(false));
  };

  // 🔹 Export PDF
  const handleExportPDF = () => {
    if (!selectedReport) return;
    window.open(
      `${import.meta.env.VITE_API_BASE_URL}/analytics/reports/${selectedReport.id}/pdf/`,
      "_blank"
    );
  };

  useEffect(() => {
    fetchReports();
  }, []);

  if (loading) {
    return <p style={{ padding: "32px" }}>Loading reports…</p>;
  }

  if (reports.length === 0) {
    return (
      <div style={{ padding: "32px" }}>
        <button
          onClick={handleGenerateReport}
          style={{
            padding: "10px 16px",
            borderRadius: "8px",
            border: "none",
            background: "#2563eb",
            color: "#fff",
            fontWeight: 500,
            cursor: "pointer",
          }}
        >
          Generate New Report
        </button>
        <p style={{ marginTop: "16px" }}>No reports generated yet.</p>
      </div>
    );
  }

  if (!selectedReport) return null;

  return (
    <div style={{ display: "flex", gap: "24px" }}>
      {/* REPORT HISTORY */}
      <aside
        style={{
          width: "260px",
          borderRight: "1px solid #e5e7eb",
          paddingRight: "16px",
        }}
      >
        <h3 style={{ marginBottom: "12px" }}>Report History</h3>

        {reports.map((r) => (
          <div
            key={r.id}
            onClick={() => setSelectedReport(r)}
            style={{
              padding: "10px",
              marginBottom: "8px",
              borderRadius: "8px",
              cursor: "pointer",
              background:
                selectedReport.id === r.id ? "#eef2ff" : "transparent",
            }}
          >
            <strong style={{ display: "block", fontSize: "14px" }}>
              {new Date(r.generated_at).toLocaleDateString()}
            </strong>
            <span style={{ fontSize: "12px", color: "#6b7280" }}>
              {r.status_summary}
            </span>
          </div>
        ))}
      </aside>

      {/* REPORT VIEW */}
      <main className="report-container" style={{ flex: 1 }}>
        {/* ACTION BAR */}
        <div
          style={{
            display: "flex",
            justifyContent: "flex-end",
            gap: "12px",
            marginBottom: "16px",
          }}
        >
          <button
            onClick={handleExportPDF}
            style={{
              padding: "10px 16px",
              borderRadius: "8px",
              border: "1px solid #2563eb",
              background: "#fff",
              color: "#2563eb",
              fontWeight: 500,
              cursor: "pointer",
            }}
          >
            Export PDF
          </button>

          <button
            onClick={handleGenerateReport}
            style={{
              padding: "10px 16px",
              borderRadius: "8px",
              border: "none",
              background: "#2563eb",
              color: "#fff",
              fontWeight: 500,
              cursor: "pointer",
            }}
          >
            Generate New Report
          </button>
        </div>

        {/* HEADER */}
        <header className="report-header">
          <h1>{selectedReport.title}</h1>
          <p className="meta">
            Generated on{" "}
            {new Date(selectedReport.generated_at).toLocaleDateString()} •
            Generated by {selectedReport.generated_by}
          </p>
        </header>

        {/* EXECUTIVE SUMMARY */}
        <section className="report-section">
          <h2>Executive Summary</h2>
          <p>{selectedReport.executive_summary}</p>
        </section>

        {/* KEY METRICS */}
        <section className="report-section">
          <h2>Key Metrics</h2>
          <div className="metrics-grid">
            <div>
              <span>Total Donations</span>
              <strong>{selectedReport.total_donations}</strong>
            </div>
            <div>
              <span>Total Requests</span>
              <strong>{selectedReport.total_requests}</strong>
            </div>
            <div>
              <span>Donation–Request Ratio</span>
              <strong>{selectedReport.donation_request_ratio}</strong>
            </div>
            <div>
              <span>Status</span>
              <strong>{selectedReport.status_summary}</strong>
            </div>
          </div>
        </section>

        {/* SYSTEM CONCLUSION */}
        <section className="report-section">
          <h2>System Conclusion</h2>
          <p>{selectedReport.system_conclusion}</p>
        </section>
      </main>
    </div>
  );
};

export default AdminReport;
