# Generated by Django 6.0 on 2025-12-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='proof_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proof_type',
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('receiver', 'Receiver'), ('volunteer', 'Volunteer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
