# Generated by Django 6.0 on 2026-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer_code',
            field=models.CharField(blank=True, help_text='Human-friendly ID for volunteers (e.g., VOL-001)', max_length=10, null=True, unique=True),
        ),
    ]
