# Generated by Django 6.0 on 2026-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_volunteer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
