# Generated by Django 6.0 on 2026-01-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_aadhaar_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_last4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_verified',
        ),
    ]
