# Generated by Django 6.0 on 2026-01-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_aadhaar_last4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
