# Generated by Django 6.0 on 2026-02-12 12:17

import django.contrib.auth.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_aadhaar_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.SoftDeleteUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('receiver', 'Receiver'), ('volunteer', 'Volunteer'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
