# Generated by Django 6.0 on 2026-02-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_managers_user_is_deleted_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AadhaaarOTP',
            new_name='EmailOTP',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='aadhaar_verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='aadhaar_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='aadhaar_last4',
        ),
    ]
