# Generated by Django 6.0 on 2026-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_aadhaaarotp_emailotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the volunteer is available for tasks'),
        ),
    ]
