from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch


def generate_report_pdf(report):
    """
    Generates a professional PDF for an AnalyticsReport instance
    and returns a BytesIO buffer.
    """

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)

    width, height = A4
    y = height - inch

    # ===== TITLE =====
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(inch, y, report.title)

    # ===== METADATA =====
    y -= 30
    pdf.setFont("Helvetica", 10)
    pdf.drawString(inch, y, f"Generated by: {report.generated_by}")
    y -= 14
    pdf.drawString(
        inch,
        y,
        f"Period: {report.start_date} → {report.end_date}",
    )

    # ===== EXECUTIVE SUMMARY =====
    y -= 30
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(inch, y, "Executive Summary")

    y -= 18
    pdf.setFont("Helvetica", 11)
    text = pdf.beginText(inch, y)
    for line in report.executive_summary.split(". "):
        text.textLine(line)
    pdf.drawText(text)

    # ===== KEY METRICS =====
    y -= 100
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(inch, y, "Key Metrics")

    y -= 20
    pdf.setFont("Helvetica", 11)
    pdf.drawString(inch, y, f"Total Donations: {report.total_donations}")
    y -= 14
    pdf.drawString(inch, y, f"Total Requests: {report.total_requests}")
    y -= 14
    pdf.drawString(
        inch,
        y,
        f"Donation–Request Ratio: {report.donation_request_ratio}",
    )
    y -= 14
    pdf.drawString(inch, y, f"Status: {report.status_summary}")

    # ===== SYSTEM CONCLUSION =====
    y -= 30
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(inch, y, "System Conclusion")

    y -= 18
    pdf.setFont("Helvetica", 11)
    text = pdf.beginText(inch, y)
    for line in report.system_conclusion.split(". "):
        text.textLine(line)
    pdf.drawText(text)

    # ===== FINALIZE =====
    pdf.showPage()
    pdf.save()

    buffer.seek(0)
    return buffer
