# Generated by Django 6.0 on 2026-02-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('food_type', models.CharField(help_text='e.g., Prepared Meals, Dry Rations', max_length=100)),
                ('target_quantity', models.PositiveIntegerField(help_text='Target number of units/meals')),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaigndonation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigndonation',
            name='donor',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignDonation',
        ),
    ]
