# Generated by Django 6.0 on 2025-12-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_donationorder_unique_receiver_donation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
