# Generated by Django 6.0 on 2025-12-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0003_itemrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='condition',
            field=models.CharField(blank=True, choices=[('new_unused', 'New (Unused)'), ('like_new', 'Like New'), ('gently_used', 'Gently Used'), ('used_functional', 'Used but Functional'), ('refurbished', 'Refurbished')], default='gently_used', max_length=100),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='images_required',
            field=models.BooleanField(default=False, help_text='If true, donor must upload images'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='used_duration_months',
            field=models.CharField(blank=True, help_text='Duration in months (only if item is used)', max_length=100),
        ),
    ]
