# Generated by Django 6.0 on 2026-01-28 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_donationimage_image_donationimage_image_url'),
        ('receiver', '0004_itemrequest_condition_itemrequest_images_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donationorder',
            name='unique_receiver_donation_order',
        ),
        migrations.AddField(
            model_name='donationorder',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationorder',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='donation.donation'),
        ),
        migrations.AlterField(
            model_name='donationorder',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationorder',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], default='assigned', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='donationorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['assigned', 'picked_up'])), fields=('donation',), name='unique_active_donation_order'),
        ),
    ]
