# Generated by Django 6.0 on 2026-01-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0005_remove_donationorder_unique_receiver_donation_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationorder',
            name='drop_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
