# Generated by Django 6.0 on 2026-02-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0007_alter_donationorder_status_volunteerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationorder',
            name='delivery_type',
            field=models.CharField(choices=[('self_pickup', 'Self Pickup'), ('volunteer', 'Volunteer Delivery')], default='volunteer', max_length=20),
        ),
    ]
