# Generated by Django 6.0 on 2026-02-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0008_donationorder_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='delivery_preference',
            field=models.CharField(choices=[('self_pickup', 'Self Pickup'), ('volunteer', 'Volunteer Delivery')], default='volunteer', max_length=20),
        ),
    ]
