# Generated by Django 6.0 on 2026-02-19 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_delete_donationtransaction'),
        ('receiver', '0009_itemrequest_delivery_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='donation.donation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-similarity_score', '-created_at'],
                'unique_together': {('donation', 'receiver')},
            },
        ),
    ]
