from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework import status
from django.db.models import Sum, Count, Avg, Q
from django.utils.timezone import now
from datetime import timedelta
from rest_framework.generics import ListAPIView
from django.http import FileResponse

from donation.models import Donation
from donation.serializers import PublicDonationSerializer
from receiver.models import ItemRequest, RecommendedDonation, DonationOrder
from analytics.models import AnalyticsReport, DemandPrediction
from analytics.serializers import AnalyticsReportSerializer, DemandPredictionSerializer
from analytics.utils.report_pdf import generate_report_pdf

class PredictiveAnalyticsAPIView(APIView):
    """
    Returns the latest demand predictions generated by the ML model.
    """
    permission_classes = [IsAdminUser]

    def get(self, request):
        predictions = DemandPrediction.objects.all()
        serializer = DemandPredictionSerializer(predictions, many=True)
        
        # Also return a summary of available categories for trend analysis
        return Response({
            "target_month": predictions.first().target_month if predictions.exists() else None,
            "predictions": serializer.data,
            "count": predictions.count()
        })

class CategoryBalanceAnalyticsAPIView(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        start_date = request.query_params.get('start_date')
        end_date = request.query_params.get('end_date')

        if not start_date or not end_date:
            return Response(
                {"error": "start_date and end_date are required"},
                status=status.HTTP_400_BAD_REQUEST
            )

        # --- Aggregate donations ---
        donation_qs = (
            Donation.objects
            .filter(
                status='verified',
                created_at__date__range=[start_date, end_date]
            )
            .values('category')
            .annotate(total_donated=Sum('quantity'))
        )

        # --- Aggregate requests ---
        request_qs = (
            ItemRequest.objects
            .filter(
                status='approved',
                created_at__date__range=[start_date, end_date]
            )
            .values('category')
            .annotate(total_requested=Sum('quantity'))
        )

        # --- Merge by category ---
        category_map = {}

        for d in donation_qs:
            category_map[d['category']] = {
                "category": d['category'],
                "donated": d['total_donated'],
                "requested": 0
            }

        for r in request_qs:
            if r['category'] not in category_map:
                category_map[r['category']] = {
                    "category": r['category'],
                    "donated": 0,
                    "requested": r['total_requested']
                }
            else:
                category_map[r['category']]['requested'] = r['total_requested']

        return Response({
            "start_date": start_date,
            "end_date": end_date,
            "categories": list(category_map.values())
        })

class GenerateAnalyticsReportView(APIView):
    permission_classes = [IsAdminUser]

    def post(self, request):
        days = int(request.data.get("days", 30))
        end_date = now().date()
        start_date = end_date - timedelta(days=days)

        # ---- Compute Donations ----
        total_donations = (
            Donation.objects
            .filter(
                created_at__date__gte=start_date,
                created_at__date__lte=end_date,
                status__in=["verified", "assigned", "delivered"]
            )
            .aggregate(total=Sum("quantity"))["total"] or 0
        )

        # ---- Compute Requests ----
        total_requests = (
            ItemRequest.objects
            .filter(
                created_at__date__gte=start_date,
                created_at__date__lte=end_date,
                status__in=["approved", "completed"]
            )
            .aggregate(total=Sum("quantity"))["total"] or 0
        )

        # ---- Ratio & Status ----
        ratio = round(
            total_donations / total_requests, 2
        ) if total_requests > 0 else 0

        if ratio == 0:
            status_summary = "No demand recorded"
        elif ratio < 1:
            status_summary = "Demand-heavy"
        elif ratio == 1:
            status_summary = "Balanced"
        else:
            status_summary = "Supply-heavy"

        # ---- Auto-generated Text ----
        executive_summary = (
            f"This report analyzes donation and request activity between "
            f"{start_date} and {end_date}. During this period, the system "
            f"recorded {total_donations} donated items and "
            f"{total_requests} requested items, indicating a "
            f"{status_summary.lower()} state."
        )

        system_conclusion = (
            f"Based on the observed donation–request ratio of {ratio}, "
            f"the system currently reflects a {status_summary.lower()} "
            f"condition. Administrative action may be required depending "
            f"on ongoing trends."
        )

        # ---- Create Report ----
        report = AnalyticsReport.objects.create(
            title=f"Donation & Request Analysis ({start_date} → {end_date})",
            generated_by=request.user,
            start_date=start_date,
            end_date=end_date,
            total_donations=total_donations,
            total_requests=total_requests,
            donation_request_ratio=ratio,
            status_summary=status_summary,
            executive_summary=executive_summary,
            system_conclusion=system_conclusion,
        )

        return Response(
            {
                "id": report.id,
                "title": report.title,
                "status": "Report generated successfully"
            },
            status=status.HTTP_201_CREATED
        )
class AnalyticsReportListView(ListAPIView):
    queryset = AnalyticsReport.objects.all()
    serializer_class = AnalyticsReportSerializer
    permission_classes = [IsAdminUser]
    
class ReportPDFDownloadView(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request, report_id):
        report = AnalyticsReport.objects.get(id=report_id)
        pdf_buffer = generate_report_pdf(report)

        return FileResponse(
            pdf_buffer,
            as_attachment=True,
            filename=f"{report.title}.pdf",
            content_type="application/pdf",
        )


# ==================================================
# AI RECOMMENDATION VIEWS
# ==================================================

class ReceiverRecommendationsAPIView(APIView):
    """
    Get AI-powered donation recommendations for receivers
    Based on their request history AND order (receipt) history
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        # Query params
        limit = int(request.query_params.get('limit', 12))
        
        # Fetch Request & Order History
        user_requests_all = ItemRequest.objects.filter(receiver=request.user)
        user_orders_all = DonationOrder.objects.filter(receiver=request.user, status__in=['assigned', 'picked_up', 'delivered'])
        
        # Combined activity count
        history_count = user_requests_all.count() + user_orders_all.count()
        
        # ❌ Less than 1 items needed for profile? Let's use 1 to ensure some history exists.
        if history_count < 1:
            # Fallback for completely new users - show recent verified items
            donations = Donation.objects.filter(
                status='verified',
                donation_type='item'
            ).exclude(
                orders__isnull=False
            ).exclude(
                donor=request.user
            ).order_by('-created_at')[:limit]
            
            serializer = PublicDonationSerializer(donations, many=True)
            return Response({
                "recommendations": serializer.data,
                "count": len(donations),
                "message": "Start requesting items to get personalized AI recommendations! Showing recent items."
            }, status=status.HTTP_200_OK)
            
        # 1️⃣ Analyze Combined History for Profile
        from collections import Counter
        
        # Get all categories from both requests and orders
        pref_categories_list = [c.strip().lower() for c in list(user_requests_all.values_list('category', flat=True)) if c] + \
                             [c.strip().lower() for c in list(user_orders_all.values_list('donation__category', flat=True)) if c]
        
        cat_counts = Counter(pref_categories_list)
        preferred_categories = [cat for cat, count in cat_counts.most_common(5)]
        
        # Conditions preference
        pref_conditions_list = [c for c in list(user_requests_all.values_list('condition', flat=True)) if c] + \
                              [c for c in list(user_orders_all.values_list('donation__condition', flat=True)) if c]
        cond_counts = Counter(pref_conditions_list)
        preferred_conditions = [cond for cond, count in cond_counts.most_common(3)]
        
        # Past Item Names for similarity matching
        past_item_names = list(user_requests_all.values_list('item_name', flat=True)[:10]) + \
                         list(user_orders_all.values_list('donation__item_name', flat=True)[:10])
        
        import difflib
        
        # 2️⃣ Get available donations
        # We prioritize 'verified' ones, but also look for 'pending' that have explicit matching engine tags
        recommended_ids = RecommendedDonation.objects.filter(
            receiver=request.user
        ).values_list('donation_id', flat=True)
        
        available = Donation.objects.filter(
            Q(status='verified') | Q(
                id__in=recommended_ids
            ),
            donation_type='item'
        ).exclude(
            orders__isnull=False
        ).exclude(
            donor=request.user # Exclude user's own items
        ).distinct().order_by('-created_at')
        
        if not available.exists():
            return Response({
                "recommendations": [],
                "count": 0,
                "message": "No donations available at the moment."
            }, status=status.HTTP_200_OK)
        
        # 3️⃣ Score each donation based on combined profile
        scored = []
        for donation in available:
            score = 0.0
            d_cat = donation.category.strip().lower()
            
            # Category match (Crucial - 60%)
            if d_cat in preferred_categories:
                idx = preferred_categories.index(d_cat)
                score += (5 - idx) * 0.12  # Up to 0.60
            elif any(p_cat in d_cat or d_cat in p_cat for p_cat in preferred_categories):
                score += 0.25 # Partial category match
            
            # Condition match (Bonus 15%)
            if donation.condition in preferred_conditions:
                score += 0.15
            
            # Freshness (Bonus 5%)
            if (now() - donation.created_at).days < 3:
                score += 0.05
            
            # --- Similarity Match (Bonus 20%) ---
            best_sim = 0.0
            for name in past_item_names:
                sim = difflib.SequenceMatcher(None, name.lower(), donation.item_name.lower()).ratio()
                if sim > best_sim:
                    best_sim = sim
            
            if best_sim > 0.6: 
                score += best_sim * 0.20 

            # Only include if there is some relevance to avoid "showing everything"
            if score > 0.15 or donation.id in recommended_ids:
                scored.append({'donation': donation, 'score': score})
        
        # 4️⃣ Sort by score & return top matches
        scored.sort(key=lambda x: x['score'], reverse=True)
        recommendations = [item['donation'] for item in scored[:limit]]
        
        serializer = PublicDonationSerializer(recommendations, many=True)
        return Response({
            "recommendations": serializer.data,
            "count": len(recommendations),
            "profile_based": True,
            "message": "Personalized recommendations based on your request and order history"
        }, status=status.HTTP_200_OK)


class ReceiverProfileInsightsAPIView(APIView):
    """
    Get receiver's preference profile based on both requests and orders
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        user_requests = ItemRequest.objects.filter(receiver=request.user)
        user_orders = DonationOrder.objects.filter(receiver=request.user, status__in=['assigned', 'picked_up', 'delivered'])
        
        if not user_requests.exists() and not user_orders.exists():
            return Response({
                "profile": None,
                "trending_categories": [],
                "message": "Start requesting or ordering items to see your preference profile"
            }, status=status.HTTP_200_OK)
        
        # Combined preferred categories
        from collections import Counter
        all_cats = [c.strip().lower() for c in list(user_requests.values_list('category', flat=True)) if c] + \
                  [c.strip().lower() for c in list(user_orders.values_list('donation__category', flat=True)) if c]
        cat_counts = Counter(all_cats)
        
        all_conds = [c for c in list(user_requests.values_list('condition', flat=True)) if c] + \
                   [c for c in list(user_orders.values_list('donation__condition', flat=True)) if c]
        cond_counts = Counter(all_conds)
        
        # 1️⃣ Build user preference profile
        total_qty = (user_requests.aggregate(Sum('quantity'))['quantity__sum'] or 0) + user_orders.count()
        avg_qty = total_qty / (user_requests.count() + user_orders.count()) if (user_requests.count() + user_orders.count()) > 0 else 0

        profile = {
            'preferred_categories': [cat.capitalize() for cat, _ in cat_counts.most_common(5)],
            'preferred_conditions': [cond for cond, _ in cond_counts.most_common(3)],
            'request_count': user_requests.count() + user_orders.count(), # Combined activity count
            'avg_quantity': round(avg_qty, 1),
        }
        
        # 2️⃣ Get trending categories across all donations
        trending = Donation.objects.filter(
            status='verified',
            donation_type='item'
        ).values('category').annotate(
            count=Count('id')
        ).order_by('-count')[:5]
        
        trending_list = [
            {'category': item['category'], 'available_count': item['count']}
            for item in trending
        ]
        
        return Response({
            "profile": profile,
            "trending_categories": trending_list
        }, status=status.HTTP_200_OK)
